export enum NAVIGATION_POINT {
    ONE = 0,
    TWO = 1,
    THREE = 2,
    FOUR = 3,
    FIVE = 4,
    SIX = 5,
    SEVEN = 6,
    EIGHT = 7,
    NINE = 8,
    CLEAR = 9,
    ZERO = 10,
    CHECKBOX = 11,
    SUBMIT = 12,
    CLOSE = 13
}

export const numberByNavigationPoint = {
    [NAVIGATION_POINT.ZERO]: "0",
    [NAVIGATION_POINT.ONE]: "1",
    [NAVIGATION_POINT.TWO]: "2",
    [NAVIGATION_POINT.THREE]: "3",
    [NAVIGATION_POINT.FOUR]: "4",
    [NAVIGATION_POINT.FIVE]: "5",
    [NAVIGATION_POINT.SIX]: "6",
    [NAVIGATION_POINT.SEVEN]: "7",
    [NAVIGATION_POINT.EIGHT]: "8",
    [NAVIGATION_POINT.NINE]: "9",

    [NAVIGATION_POINT.CLEAR]: "",
    [NAVIGATION_POINT.CHECKBOX]: "",
    [NAVIGATION_POINT.SUBMIT]: "",
    [NAVIGATION_POINT.CLOSE]: ""
};

export const navigationPointByNumber: { [key: string]: NAVIGATION_POINT } = {
    "0": NAVIGATION_POINT.ZERO,
    "1": NAVIGATION_POINT.ONE,
    "2": NAVIGATION_POINT.TWO,
    "3": NAVIGATION_POINT.THREE,
    "4": NAVIGATION_POINT.FOUR,
    "5": NAVIGATION_POINT.FIVE,
    "6": NAVIGATION_POINT.SIX,
    "7": NAVIGATION_POINT.SEVEN,
    "8": NAVIGATION_POINT.EIGHT,
    "9": NAVIGATION_POINT.NINE,
};

export const navigationMap: { [key: number]: NAVIGATION_POINT[] } = {
    // current position          UP                           DOWN                         LEFT                     RIGHT
    [NAVIGATION_POINT.ONE]:      [NAVIGATION_POINT.SUBMIT,    NAVIGATION_POINT.FOUR,       NAVIGATION_POINT.CLOSE,  NAVIGATION_POINT.TWO],
    [NAVIGATION_POINT.TWO]:      [NAVIGATION_POINT.SUBMIT,    NAVIGATION_POINT.FIVE,       NAVIGATION_POINT.ONE,    NAVIGATION_POINT.THREE],
    [NAVIGATION_POINT.THREE]:    [NAVIGATION_POINT.SUBMIT,    NAVIGATION_POINT.SIX,        NAVIGATION_POINT.TWO,    NAVIGATION_POINT.CLOSE],
    [NAVIGATION_POINT.FOUR]:     [NAVIGATION_POINT.ONE,       NAVIGATION_POINT.SEVEN,      NAVIGATION_POINT.CLOSE,  NAVIGATION_POINT.FIVE],
    [NAVIGATION_POINT.FIVE]:     [NAVIGATION_POINT.TWO,       NAVIGATION_POINT.EIGHT,      NAVIGATION_POINT.FOUR,   NAVIGATION_POINT.SIX],
    [NAVIGATION_POINT.SIX]:      [NAVIGATION_POINT.THREE,     NAVIGATION_POINT.NINE,       NAVIGATION_POINT.FIVE,   NAVIGATION_POINT.CLOSE],
    [NAVIGATION_POINT.SEVEN]:    [NAVIGATION_POINT.FOUR,      NAVIGATION_POINT.CLEAR,      NAVIGATION_POINT.CLOSE,  NAVIGATION_POINT.EIGHT],
    [NAVIGATION_POINT.EIGHT]:    [NAVIGATION_POINT.FIVE,      NAVIGATION_POINT.CLEAR,      NAVIGATION_POINT.SEVEN,  NAVIGATION_POINT.NINE],
    [NAVIGATION_POINT.NINE]:     [NAVIGATION_POINT.SIX,       NAVIGATION_POINT.ZERO,       NAVIGATION_POINT.EIGHT,  NAVIGATION_POINT.CLOSE],
    [NAVIGATION_POINT.CLEAR]:    [NAVIGATION_POINT.SEVEN,     NAVIGATION_POINT.CHECKBOX,   NAVIGATION_POINT.CLOSE,  NAVIGATION_POINT.ZERO],
    [NAVIGATION_POINT.ZERO]:     [NAVIGATION_POINT.NINE,      NAVIGATION_POINT.CHECKBOX,   NAVIGATION_POINT.CLEAR,  NAVIGATION_POINT.CLOSE],
    [NAVIGATION_POINT.CHECKBOX]: [NAVIGATION_POINT.CLEAR,     NAVIGATION_POINT.SUBMIT,     NAVIGATION_POINT.CLOSE,  NAVIGATION_POINT.CLOSE],
    [NAVIGATION_POINT.SUBMIT]:   [NAVIGATION_POINT.CHECKBOX,  NAVIGATION_POINT.ONE,        NAVIGATION_POINT.CLOSE,  NAVIGATION_POINT.CLOSE],
    [NAVIGATION_POINT.CLOSE]:    [NAVIGATION_POINT.FIVE,      NAVIGATION_POINT.FIVE,       NAVIGATION_POINT.FIVE,   NAVIGATION_POINT.FIVE],
};